apiVersion : apps/v1
kind: Deployment
metadata:
  name: image-classify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classify
  template:
    metadata:
      labels:
        app: image-classify
    spec:
      containers:
        - name: image-classify-container
          image: adityax123/image-classify-docker-image:1.1.2
          ports:
          - containerPort: 8501

