apiVersion: v1
kind: Service

metadata:
  name: image-classify-service

spec:
  type: LoadBalancer
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      
  selector:
    app: image-classify
    type: front-end
