apiVersion: v1
kind: Service
metadata:
    name: image-classify
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8501
    selector:
        app: image-classify









