apiVersion: v1
kind: Service

metadata:
  name: image-classify-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30007
  selector:
    app: image-classify
    type: front-end